import type { Organizer, OrgStatus, StatusConfig, EventColorConfig } from "./types";

export { type Organizer, type OrgStatus, type StatusConfig, type EventColorConfig };

export const ORGANIZERS: Organizer[] = [
  {
    id: "ORG-001",
    name: "Sarah Jenkins",
    email: "s.jenkins@asiangames2026.org",
    photo: "https://images.unsplash.com/photo-1771240730126-594a8ab66be1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=200",
    role: "Swimming Coordinator",
    event: "Asian Games 2026",
    eventEmoji: "🏆",
    division: "Swimming",
    divisionEmoji: "🏊",
    accessKey: "AG26-COORD-SWIM",
    lastLogin: "Feb 24, 2026 · 14:03",
    lastLoginRelative: "2 mins ago",
    status: "active",
    permissions: ["View Results", "Edit Schedule", "Manage Roster"],
  },
  {
    id: "ORG-002",
    name: "Ahmad Dani",
    email: "ahmad.dani@unesacup.id",
    photo: "https://images.unsplash.com/photo-1648448942225-7aa06c7e8f79?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=200",
    role: "Venue Manager",
    event: "Unesa Cup",
    eventEmoji: "⚽",
    division: "Futsal",
    divisionEmoji: "🥅",
    accessKey: "UNESA-MGR-FTSL",
    lastLogin: "Feb 24, 2026 · 13:51",
    lastLoginRelative: "14 mins ago",
    status: "active",
    permissions: ["View Results", "Manage Venue", "Edit Schedule"],
  },
  {
    id: "ORG-003",
    name: "Marcus Reid",
    email: "m.reid@asiangames2026.org",
    photo: "https://images.unsplash.com/photo-1622169804256-0eb6873ff441?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=200",
    role: "Head Referee",
    event: "Asian Games 2026",
    eventEmoji: "🏆",
    division: "Basketball — Men",
    divisionEmoji: "🏀",
    accessKey: "AG26-REF-BSKT",
    lastLogin: "Feb 24, 2026 · 13:05",
    lastLoginRelative: "1 hr ago",
    status: "active",
    permissions: ["View Results", "Publish Scores"],
  },
  {
    id: "ORG-004",
    name: "Linda Hartono",
    email: "l.hartono@asiangames2026.org",
    photo: "https://images.unsplash.com/photo-1659353220612-2f4adc1d6d42?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=200",
    role: "Event Coordinator",
    event: "Asian Games 2026",
    eventEmoji: "🏆",
    division: "Athletics",
    divisionEmoji: "🏃",
    accessKey: "AG26-COORD-ATL",
    lastLogin: "Feb 24, 2026 · 11:10",
    lastLoginRelative: "3 hrs ago",
    status: "active",
    permissions: ["View Results", "Edit Schedule", "Manage Roster", "Publish Scores"],
  },
  {
    id: "ORG-005",
    name: "Mei Lin Chen",
    email: "mei.chen@owinter2026.org",
    photo: "https://images.unsplash.com/photo-1740153204804-200310378f2f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=200",
    role: "Operations Analyst",
    event: "Olympic Winter",
    eventEmoji: "⛷️",
    division: "Alpine Skiing",
    divisionEmoji: "🎿",
    accessKey: "OW26-OPS-SKI",
    lastLogin: "Feb 23, 2026 · 20:44",
    lastLoginRelative: "Yesterday",
    status: "active",
    permissions: ["View Results", "Analytics Read"],
  },
  {
    id: "ORG-006",
    name: "Roberto Alves",
    email: "r.alves@unesacup.id",
    photo: "https://images.unsplash.com/photo-1747994723854-a77c99997656?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=200",
    role: "Field Supervisor",
    event: "Unesa Cup",
    eventEmoji: "⚽",
    division: "Football",
    divisionEmoji: "⚽",
    accessKey: "UNESA-SUP-FTBL",
    lastLogin: "Feb 21, 2026 · 09:14",
    lastLoginRelative: "3 days ago",
    status: "revoked",
    permissions: ["View Results"],
  },
  {
    id: "ORG-007",
    name: "Priya Sharma",
    email: "p.sharma@asiangames2026.org",
    photo: "https://images.unsplash.com/photo-1770627000564-3feb36aecbcd?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=200",
    role: "Technical Director",
    event: "Asian Games 2026",
    eventEmoji: "🏆",
    division: "Gymnastics",
    divisionEmoji: "🤸",
    accessKey: "AG26-DIR-GYM",
    lastLogin: "Feb 24, 2026 · 14:00",
    lastLoginRelative: "5 mins ago",
    status: "active",
    permissions: ["View Results", "Edit Schedule", "Manage Roster", "Publish Scores", "Admin Panel"],
  },
  {
    id: "ORG-008",
    name: "David Torres",
    email: "d.torres@unesacup.id",
    photo: "https://images.unsplash.com/photo-1622169804256-0eb6873ff441?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=200",
    role: "Logistics Manager",
    event: "Unesa Cup",
    eventEmoji: "⚽",
    division: "Basketball",
    divisionEmoji: "🏀",
    accessKey: "UNESA-LOG-BSKT",
    lastLogin: "Feb 24, 2026 · 13:23",
    lastLoginRelative: "42 mins ago",
    status: "active",
    permissions: ["View Results", "Manage Venue"],
  },
];

export const EVENTS = ["All Events", "Asian Games 2026", "Unesa Cup", "Olympic Winter"];
export const DIVISIONS = [
  "All Divisions",
  "Swimming",
  "Athletics",
  "Basketball — Men",
  "Basketball",
  "Gymnastics",
  "Futsal",
  "Football",
  "Alpine Skiing",
];

export const STATUS_CFG: Record<OrgStatus, StatusConfig> = {
  active:    { label: "Active",    dot: "#22C55E", bg: "#DCFCE7", text: "#15803D", border: "#BBF7D0" },
  revoked:   { label: "Revoked",   dot: "#EF4444", bg: "#FEE2E2", text: "#DC2626", border: "#FECACA" },
  suspended: { label: "Suspended", dot: "#F59E0B", bg: "#FEF3C7", text: "#92400E", border: "#FDE68A" },
};

export const EVENT_COLOR: Record<string, EventColorConfig> = {
  "Asian Games 2026": { bg: "#EFF6FF", text: "#1D4ED8", border: "#BFDBFE" },
  "Unesa Cup":        { bg: "#F0FDF4", text: "#15803D", border: "#BBF7D0" },
  "Olympic Winter":   { bg: "#F1F5F9", text: "#475569", border: "#E2E8F0" },
};
